
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIV LPAR MINUS MUL NUMBER PLUS RPARS : EE : E PLUS TE : E MINUS TE : MINUS E PLUS TE : MINUS E MINUS TE : TT : T MUL FT : T DIV FT : FF : NUMBERF : LPAR E RPAR'
    
_lr_action_items = {'MINUS':([0,2,3,4,5,6,7,12,13,14,15,16,17,20,21,22,],[4,9,-6,4,-9,-10,4,18,9,-2,-3,-7,-8,-11,-3,-2,]),'NUMBER':([0,4,7,8,9,10,11,18,19,],[6,6,6,6,6,6,6,6,6,]),'LPAR':([0,4,7,8,9,10,11,18,19,],[7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,5,6,14,15,16,17,20,21,22,],[0,-1,-6,-9,-10,-2,-3,-7,-8,-11,-5,-4,]),'PLUS':([2,3,5,6,12,13,14,15,16,17,20,21,22,],[8,-6,-9,-10,19,8,-2,-3,-7,-8,-11,-3,-2,]),'RPAR':([3,5,6,13,14,15,16,17,20,21,22,],[-6,-9,-10,20,-2,-3,-7,-8,-11,-5,-4,]),'MUL':([3,5,6,14,15,16,17,20,21,22,],[10,-9,-10,10,10,-7,-8,-11,10,10,]),'DIV':([3,5,6,14,15,16,17,20,21,22,],[11,-9,-10,11,11,-7,-8,-11,11,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'E':([0,4,7,],[2,12,13,]),'T':([0,4,7,8,9,18,19,],[3,3,3,14,15,21,22,]),'F':([0,4,7,8,9,10,11,18,19,],[5,5,5,5,5,16,17,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> E','S',1,'p_S','plus_minus_multiply_devide_uminus.py',18),
  ('E -> E PLUS T','E',3,'p_E_plus_T','plus_minus_multiply_devide_uminus.py',21),
  ('E -> E MINUS T','E',3,'p_E_MINUS_T','plus_minus_multiply_devide_uminus.py',25),
  ('E -> MINUS E PLUS T','E',4,'p_MINUS_E_plus_T','plus_minus_multiply_devide_uminus.py',30),
  ('E -> MINUS E MINUS T','E',4,'p_MINUS_E_MINUS_T','plus_minus_multiply_devide_uminus.py',35),
  ('E -> T','E',1,'p_E_T','plus_minus_multiply_devide_uminus.py',39),
  ('T -> T MUL F','T',3,'p_T_MUL_F','plus_minus_multiply_devide_uminus.py',43),
  ('T -> T DIV F','T',3,'p_T_DIV_F','plus_minus_multiply_devide_uminus.py',47),
  ('T -> F','T',1,'p_T_F','plus_minus_multiply_devide_uminus.py',52),
  ('F -> NUMBER','F',1,'p_F_a','plus_minus_multiply_devide_uminus.py',56),
  ('F -> LPAR E RPAR','F',3,'p_F_lpar_E_rpar','plus_minus_multiply_devide_uminus.py',60),
]
