
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN DIV LPAR MINUS MUL NAME NUMBER PLUS POWER RPARU : NAME ASSIGN ES : UF : NAMES : EE : E PLUS TE : E MINUS TE : TT : T MUL FT : T DIV FT : FF : MINUS NUMBERF : NUMBER POWER F F : NUMBERF : LPAR E RPAR'
    
_lr_action_items = {'NAME':([0,3,10,11,12,13,14,16,],[2,4,4,4,4,4,4,4,]),'$end':([1,4,5,6,8,9,15,18,19,20,21,22,23,],[0,-3,-1,-7,-10,-13,-11,-5,-6,-8,-9,-12,-14,]),'ASSIGN':([2,],[3,]),'MINUS':([3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,],[7,-3,12,-7,-10,-13,7,7,7,7,7,-11,7,12,-5,-6,-8,-9,-12,-14,]),'NUMBER':([3,7,10,11,12,13,14,16,],[9,15,9,9,9,9,9,9,]),'LPAR':([3,10,11,12,13,14,16,],[10,10,10,10,10,10,10,]),'MUL':([4,6,8,9,15,18,19,20,21,22,23,],[-3,13,-10,-13,-11,13,13,-8,-9,-12,-14,]),'DIV':([4,6,8,9,15,18,19,20,21,22,23,],[-3,14,-10,-13,-11,14,14,-8,-9,-12,-14,]),'PLUS':([4,5,6,8,9,15,17,18,19,20,21,22,23,],[-3,11,-7,-10,-13,-11,11,-5,-6,-8,-9,-12,-14,]),'RPAR':([4,6,8,9,15,17,18,19,20,21,22,23,],[-3,-7,-10,-13,-11,23,-5,-6,-8,-9,-12,-14,]),'POWER':([9,],[16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'U':([0,],[1,]),'E':([3,10,],[5,17,]),'T':([3,10,11,12,],[6,6,18,19,]),'F':([3,10,11,12,13,14,16,],[8,8,8,8,20,21,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> U","S'",1,None,None,None),
  ('U -> NAME ASSIGN E','U',3,'p_ASSIGN_S','Full calculator.py',26),
  ('S -> U','S',1,'p_S_U','Full calculator.py',31),
  ('F -> NAME','F',1,'p_F_NAME','Full calculator.py',34),
  ('S -> E','S',1,'p_S','Full calculator.py',37),
  ('E -> E PLUS T','E',3,'p_E_plus_T','Full calculator.py',41),
  ('E -> E MINUS T','E',3,'p_E_MINUS_T','Full calculator.py',45),
  ('E -> T','E',1,'p_E_T','Full calculator.py',50),
  ('T -> T MUL F','T',3,'p_T_MUL_F','Full calculator.py',54),
  ('T -> T DIV F','T',3,'p_T_DIV_F','Full calculator.py',59),
  ('T -> F','T',1,'p_T_F','Full calculator.py',65),
  ('F -> MINUS NUMBER','F',2,'p_F_MINUS_a','Full calculator.py',70),
  ('F -> NUMBER POWER F','F',3,'p_F_power_E','Full calculator.py',75),
  ('F -> NUMBER','F',1,'p_F_a','Full calculator.py',80),
  ('F -> LPAR E RPAR','F',3,'p_F_lpar_E_rpar','Full calculator.py',84),
]
